friends/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('send-request/<id>/', views.send_friend_request, name='send-request'),
	path('cancel-request/<id>/', views.cancel_friend_request, name='cancel-request'),
	path('accept-request/<id>/', views.accept_friend_request, name='accept-request'),
	path('reject-request/<id>/', views.reject_friend_request, name='reject-request'),
	path('remove-friend/<id>/', views.remove_friend, name='remove-friend'),
	path('block-user/<id>/', views.block_user, name='block_user'),
	path('unblock-user/<id>/', views.unblock_user, name='unblock_user'),
]

home/urls.py
from django.urls import path
from home.views import HomeView
from . import views

urlpatterns = [
	path('home/', HomeView.as_view(), name='home'),
	path('search_user', views.search_user, name='search_user'),
]

social_network/urls.py
from django.contrib import admin
from django.urls import path, include
from social_network import views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500,handler403, handler400


urlpatterns = [
	path('', views.login_redirect, name='login_redirect'),
    path('admin/', admin.site.urls),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('', include(('home.urls', 'home'), namespace='home')),
    path('profile/', include(('userprofile.urls', 'userprofile'), namespace='userprofile')),
    path('posts/', include(('posts.urls', 'posts'), namespace='posts')),
    path('comments/', include(('comments.urls', 'comments'), namespace='comments')),
    path('friends/', include(('friends.urls', 'friends'), namespace='friends')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userprofile/urls.py
from django.urls import path

from django.contrib.auth import views as auth_views
from . import views

urlpatterns =[
	path('', views.view_profile, name='view_profile'),
	path('view/<pk>/', views.view_profile, name='view_profile_with_pk'),
	path('update/', views.edit_profile, name='edit_profile'),
	path('user/changepassword/', views.change_password, name='change_password'),
	]

userprofile/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from datetime import date
from friendship.models import Friend, Block

# Create your models here.
class UserProfileManager(models.Manager):
	def get_queryset(self):
		return super(UserProfileManager, self).get_queryset().filter(city='Kanpur')

def upload_location(instance, filename):
	return "profile_images/%s/%s" % (instance.user, filename)

class UserProfile(models.Model):
	gender_choices = (
			('Male', 'Male'),
			('Female', 'Female'),
			('Custom', 'Custom')
			)
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	description = models.CharField(max_length=150, default='Exploring World!', null=True, blank=True)
	education = models.CharField(max_length=50, default='', null=True, blank=True)
	graduated = models.NullBooleanField(default=True)
	company = models.CharField(max_length=50, default='', null=True, blank=True)
	still_work_here = models.NullBooleanField()
	hometown = models.CharField(max_length=30, default='', null=True, blank=True)
	current_city = models.CharField(max_length=30, default='', null=True, blank=True)
	image = models.ImageField(default='profile_images/default.jpg',upload_to=upload_location,null=True, blank=True)
	website = models.URLField(default='', blank=True, null=True)
	gender = models.CharField(max_length=10, choices=gender_choices, null=True, blank=True)
	has_previously_logged_in = models.BooleanField(default=False)


	#kanpur = UserProfileManager()

	def __str__(self):
		return self.user.username

	@property
	def profilepic_or_default(self, default_path="profile_images/default.jpg"):
		if self.image:
			return self.image
		return default_path

	@property
	def friends(self):
		instance = self.user
		qs = Friend.objects.friends(instance)
		return qs

	@property
	def friends_count(self):
		instance = self.friends
		return len(instance)

	@property
	def friend_requests(self):
		qs = Friend.objects.unrejected_requests(user=self.user)
		return [q.from_user for q in qs]

	@property
	def fr_count(self):
		instance = self.friend_requests
		return len(instance)
		
	@property
	def sent_requests(self):
		qs = Friend.objects.sent_requests(user=self.user)
		return [q.to_user for q in qs]

	@property
	def sr_count(self):
		instance = self.sent_requests
		return len(instance)

	@property
	def blocks(self):
		instance = self.user
		qs = Block.objects.blocking(instance)
		return qs

def create_profile(sender, **kwargs):
	if kwargs['created']:
		user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)

userprofile/forms.py
from django.contrib.auth.models import User

from django import forms
#from django.contrib.auth.forms import UserChangeForm

from userprofile.models import UserProfile


class UserUpdateForm(forms.ModelForm):
	class Meta:
		model = User
		fields = [
		'username', 
		'first_name',
		'last_name',
		'email'
		]


class UpdateProfileForm(forms.ModelForm):
	image = forms.ImageField(label='Change Avatar',required=False, 
		error_messages = {'invalid':"Image files only"}, 
		widget=forms.FileInput()
		)

	class Meta:
		model = UserProfile
		fields = [
		'image',
		'description',
		'education',
		'graduated',
		'company',
		'still_work_here',
		'hometown',
		'current_city',
		'website',
		'gender',
		]

		labels = {
		'description': 'Bio',
		'education': 'School/College',
		'graduated': 'Graduated?',
		'company': 'Workplace/Company',
		'still_work_here': 'Still work here?',
		'hometown': 'Hometown',
		'current_city': 'Current City',
		'website': 'Website',
		}

userprofile/views.py
from django.contrib.auth.models import User

from django.shortcuts import render, redirect
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
#from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import HttpResponse, Http404

from userprofile.forms import UserUpdateForm, UpdateProfileForm

from posts.models import Post
from friendship.models import Friend, Follow, Block, FriendshipRequest

# Create your views here.

def view_profile(request, pk=None):
	current_page = 'profile'

	if pk:
		user = User.objects.get(pk=pk)
	else:
		user = request.user

	me = request.user.userprofile

	if request.user in user.userprofile.blocks or user in me.blocks:
		reponse = HttpResponse("Permission denied.")
		reponse.status_code = 403
		return reponse

	posts = Post.objects.filter(user=user).order_by('-created')
	
	args = {'user': user,
		'posts': posts,
		'current_page':current_page,
		'me': me,
		}
	return render(request, 'userprofile/profile.html', args)

def edit_profile(request):
	if request.method == 'POST':
		u_form = UserUpdateForm(request.POST, instance=request.user)
		p_form = UpdateProfileForm(request.POST,
								request.FILES,
								instance=request.user.userprofile)
		if u_form.is_valid() and p_form.is_valid():
			u_form.save()
			p_form.save()
			messages.success(request, "Profile successfully updated!")
		else:
			messages.error(request, "Profile not updated. Enter valid data!")
		return redirect('userprofile:edit_profile')
	else:
		u_form = UserUpdateForm(instance=request.user)
		p_form = UpdateProfileForm(instance=request.user.userprofile)

	args = {'u_form': u_form, 'p_form': p_form}
	return render(request, 'userprofile/edit_profile.html', args)

def change_password(request):
	if request.method == 'POST':
		form = PasswordChangeForm(data=request.POST, user=request.user)
		if form.is_valid():
			form.save()
			update_session_auth_hash(request, form.user)
			messages.success(request, "Password successfully changed!")
			return redirect('home:home')
		else:
			messages.error(request, "Password not changed. Enter a valid password")
			return redirect('userprofile:change_password')
	else:
		form = PasswordChangeForm(user=request.user)
		args = {'form': form, }
		return render(request, 'userprofile/change_password.html', args)

userprofile/templates/userprofile/change_password.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block head %}
<title>Change password</title>
{% endblock %}

{% block body %}

<div class="row justify-content-center">
	<div class="col-md-6">
		<div class="content-section">
			<form method="POST">
				{% csrf_token %}
				<fieldset class="form-group">
					<legend class="border-bottom mb-4">Change Password</legend>
					{{ form|crispy }}
				</fieldset>
				<div class="form-group">
					<button class="btn btn-outline-info" type="submit">Change</button>
				</div>
			</form>
			<div class="border-top pt-3">
				<small class="text-muted">
					Don't want to change password? <a class="ml-2" href="{% url 'home:home' %}">Cancel</a>
				</small>
			</div>
		</div>

	</div>
</div>

{% endblock %}

userprofile/templates/userprofile/edit_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block head %}
<title>Edit Profile</title>
{% endblock %}

{% block body %}

<div class="row justify-content-center">
	<div class="col-md-6">
		<div>
			<div class="card-body">
				<a class="thumbnail" data-image-id="" data-toggle="modal" data-title="{{user.first_name}}'s photo"
                   data-image="{{user.userprofile.image.url}}"
                   data-target="#display-profile-pic-{{user.pk}}">
					<img class="mx-auto d-block profile-page-profile-pic" src="{{ user.userprofile.image.url }}" alt="{{user.first_name}}">
				</a>
			</div>
			<form method="POST" enctype="multipart/form-data">
				{% csrf_token %}
				<div class="small-text mb-4 text-center">
					
					<a class="thumbnail" data-image-id="" data-toggle="modal" data-target="#change-profile-pic-{{user.pk}}">
	                   <button class="btn btn-info btn-sm">Change Photo <i class="fas fa-camera"></i></button>
	               </a>

				</div>

				{% include 'extras/picture_updation_modals.html' %}

				<fieldset class="form-group">
					<legend class="border-bottom mb-4">Update Profile Info</legend>
						{{u_form.username|as_crispy_field}}
						<div class="form-row">
							<div class="form-group col-md-6 mb-0">
								{{u_form.first_name|as_crispy_field}}
							</div>
							<div class="form-group col-md-6 mb-0">
								{{u_form.last_name|as_crispy_field}}
							</div>
						</div>
						{{u_form.email|as_crispy_field}}
						{{p_form.description|as_crispy_field}}
						<div class="form-row">
							<div class="form-group col-md-8 mb-0">
								{{p_form.education|as_crispy_field}}
							</div>
							<div class="form-group col-md-4 mb-0">
								{{p_form.graduated|as_crispy_field}}
							</div>
						</div>
						<div class="form-row">
							<div class="form-group col-md-8 mb-0">
								{{p_form.company|as_crispy_field}}
							</div>
							<div class="form-group col-md-4 mb-0">
								{{p_form.still_work_here|as_crispy_field}}
							</div>
						</div>
						<div class="form-row">
							<div class="form-group col-md-6 mb-0">
								{{p_form.hometown|as_crispy_field}}
							</div>
							<div class="form-group col-md-6 mb-0">
								{{p_form.current_city|as_crispy_field}}
							</div>
						</div>
						<div class="form-row">
							<div class="form-group col-md-6 mb-0">
								{{p_form.gender|as_crispy_field}}
							</div>
						</div>

				</fieldset>
				<div class="py-3">
					<button class="btn btn-outline-info" type="submit">Update</button>
					<a href="{% url 'userprofile:view_profile' %}">
						<button class="btn btn-outline-info" type="button">Cancel</button>
					</a>
				</div>
				<div class="border-top pt-3">
					<small class="text-muted">
						*Do fill the the mandatory fields. <a href="{% url 'userprofile:view_profile' %}">Click here</a> to head to Profile.
					</small>
				</div>
			</form>
		</div>
	</div>
</div>
<br><br><br>


{% endblock %}  

userprofile/templates/userprofile/profile-actions.html


<!-- profile actions modal -->
<div class="modal fade text-center" id="profile_actions_{{user.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-body text-center">
                <p class="border-bottom"><a data-toggle="modal" data-target="#block_user_{{user.id}}" >Block</a></p>
                <p class="border-bottom"><a style="color:inherit;" href="">Send Message</a></p>
                <p class="border-bottom mb-0"><a data-dismiss="modal">Cancel</a></p>
            </div>
        </div>
    </div>
</div>

<!-- block user modal -->
	<div class="modal fade text-center" id="block_user_{{user.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
	    <div class="modal-dialog modal-dialog-centered" role="document">
	        <div class="modal-content text-center mx-auto" style="width: 400px;">
	            <div class="modal-body pt-4">
	                <img src="{{user.userprofile.image.url}}" alt="user.get_full_name" class="rounded-circle mini-profile-pic mr-0">
	                {% if user in me.friends %}
	                <p class="mt-2">Are you sure you want to block <span class="fw-55">@{{user.username}}</span>? This will unfriend the user.</p>
	                {% else %}
	                <p class="mt-2">Are you sure you want to block <span class="fw-55">@{{user.username}}</span>?</p>
	                {% endif %}
	            </div>
	            <div class="modal-footer py-2">
	                <div class="row w-100">
	                	<div class="col-6 border-right">
	                		<a data-dismiss="modal">Cancel</a>
	                	</div>
	                	<div class="col-6">
	                		<a href="{% url 'friends:block_user' id=user.id %}">Block</a>
	                	</div>
	                </div>
	            </div>
	        </div>
	    </div>
	</div>

userprofile/templates/userprofile/profile.html
{% extends 'base.html' %}

{% block head %}
	<title>{{user.username}}</title>
{% endblock %}

{% block body %}

<div class="row justify-content-center">
	
	<div class="col-lg-4 col-md-4">

		{% if user != request.user and user in me.friend_requests %}
		<div class="text-center mt-1 mb-3">
			<p class="instabook-color mb-1"> {{user.username}} wants to be friends with you.</p>
			<a href="{% url 'friends:accept-request' id=user.id  %}">
				<button class="btn btn-default btn-sm px-3"><span class="fw-55">Confirm Request</span></button>
			</a>
			<a href="{% url 'friends:reject-request' id=user.id  %}">
				<button class="btn btn-default btn-sm px-3"><span class="fw-55">Reject</span></button>
			</a>
		</div>
		{% endif %}

		<a class="thumbnail" data-image-id="" data-toggle="modal" data-title="{{user.first_name}}'s photo"
                   data-image="{{user.userprofile.image.url}}"
                   data-target="#display-profile-pic-{{user.pk}}">
			<img class="mx-auto mb-3 mt-2 d-block profile-page-profile-pic" src="{{ user.userprofile.image.url }}" alt="{{user.get_full_name}}">
		</a>

		{% if user != request.user %}
		<div class="text-center mb-2">
			{% if user in friends %}
			<a data-toggle="modal" data-target="#remove_friend_{{user.id}}">
				<button class="btn btn-default btn-sm px-2"><span class="fw-55">Friends </span><i class="very-small-icon fas fa-check"></i></button>
			</a>
		
			{% elif user in me.sent_requests %}
			<a data-toggle="modal" data-target="#cancel_request_{{user.id}}">
				<button class="btn btn-default btn-sm px-3"><span class="fw-55">Requested</span></button>
			</a>

			{% elif user not in me.friend_requests %}
			<a data-toggle="modal" data-target="#send_request_{{user.id}}">
				<button class="btn btn-primary btn-sm px-3"><span class="fw-55">Request</span></button>
			</a>
			{% endif %}

			<div class="div-inline">
				<a data-toggle="modal" data-target="#profile_actions_{{user.id}}">
					<i class="fas fa-ellipsis-v px-1"></i>
				</a>
			</div>

		</div>

		{% endif %}

		<div class="card mb-3">
			<div class="card-body">
				<h4 class="lobster mb-0">{{user.username}}{% if user == request.user %}<a data-toggle="modal" data-target="#settings"><span class="icon"><i class="fas fa-cog"></i></span></a>{% endif %}</h4>

				<p class="instabook-color">{%if user.first_name %}{{user.get_full_name}}{% else %}Instabook User{% endif %}</p>
				<p>{{user.userprofile.description}}</p>

				<ul class="list-unstyled mb-0">
					{% if user.userprofile.education %}
					<li class="small-text">
						{% if user.userprofile.graduated %}
						Studied {% else %}
						Studies {% endif %}
						at <span class="link-color lobster">{{user.userprofile.education}}</span>
					</li>
					{% endif %}

					{% if user.userprofile.company %}
					<li class="small-text">
						{% if user.userprofile.still_work_here %}
						Works {% else %}
						Worked {% endif %}
						at <span class="link-color lobster">{{user.userprofile.company}}</span>
					</li>
					{% endif %}

					{% if user.userprofile.hometown %}
					<li class="small-text">
						From <span class="link-color">{{user.userprofile.hometown}}</span>
					</li>
					{% endif %}

					{% if user.userprofile.current_city %}
					<li class="small-text">
						Lives in <span class="link-color">{{user.userprofile.current_city}}</span>
					</li>
					{% endif %}

					{% if user.email %}
					<li class="small-text">
						Mail me <span class="link-color">{{user.email}}</span>
					</li>
					{% endif %}

					{% if user.userprofile.website %}
					<li class="small-text">
						Check this out <span class="link-color">
							<a href="{{user.userprofile.website}}">{{user.userprofile.website}}</a>
						</span>
					</li>
					{% endif %}

					{% if user.userprofile.gender %}
					<li class="small-text">
						Gender <span class="link-color">
							{{user.userprofile.gender}}
						</span>
					</li>
					{% endif %}

				</ul>

			</div>
		</div>

	</div>

	{% if user == request.user %}
	<!-- Settings model -->
	<div class="modal fade text-center" id="settings" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
	    <div class="modal-dialog modal-dialog-centered" role="document">
	        <div class="modal-content" style="width: 80%">
	            <div class="modal-body text-center">
	                <p class="border-bottom"><a style="color:inherit;" href="{% url 'userprofile:edit_profile' %}">Edit Profile</a></p>
	                <p class="border-bottom"><a style="color:inherit;" href="{% url 'userprofile:change_password' %}">Change Password</a></p>
	                <p class="border-bottom">Privacy & Security</p>
	                <p class="border-bottom mb-0"><a data-dismiss="modal">Cancel</a></p>
	            </div>
	        </div>
	    </div>
	</div>
	{% endif %}

	{% include 'extras/friend_modals.html' %}
	{% include 'extras/post_likes_modal.html' %}
	{% include 'extras/picture_updation_modals.html' %}
	{% include 'userprofile/profile-actions.html' %}

	{% if user == request.user or request.user in user.userprofile.friends %}
	<div class="col-lg-6 col-md-8 px-2 mt-2">

		{% if not posts %}

		<div class="card mb-4">
			<div class="card-body">
				<p class="small-text">
				{% if user == request.user %}
					You haven't posted anything yet! <br>
					Why not create one? <a href="{% url 'home:home' %}">Click here</a> to write your first post.
				{% else %}
					No posts to display.
				{% endif %}
				</p>

			</div>
		</div>

		{% else %}
			{% for post in posts %}
				{% include "posts/list_posts.html" %}
			{% endfor %}
		{% endif %}
	</div>
	{% endif %}
</div>

{% endblock %}