comments/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('<id>/', views.comment_thread, name='comment_thread'),
	path('delete/<int:comment_id>/<int:reply_id>/', views.comment_delete, name='comment_delete'),
]

friends/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('send-request/<id>/', views.send_friend_request, name='send-request'),
	path('cancel-request/<id>/', views.cancel_friend_request, name='cancel-request'),
	path('accept-request/<id>/', views.accept_friend_request, name='accept-request'),
	path('reject-request/<id>/', views.reject_friend_request, name='reject-request'),
	path('remove-friend/<id>/', views.remove_friend, name='remove-friend'),
	path('block-user/<id>/', views.block_user, name='block_user'),
	path('unblock-user/<id>/', views.unblock_user, name='unblock_user'),
]

home/urls.py
from django.urls import path
from home.views import HomeView
from . import views

urlpatterns = [
	path('home/', HomeView.as_view(), name='home'),
	path('search_user', views.search_user, name='search_user'),
]

posts/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('<pk>/full_post', views.view_post, name='view_post'),
	path('<pk>/edit/next?=<previous_page>/', views.edit_post, name='edit_post'),
	path('<pk>/edit/cancel/next?=<previous_page>/', views.cancel_post_activity, name='cancel_post_activity'),
	path('<pk>/delete/', views.delete_post, name='delete_post'),
	path('<pk>/<operation>/', views.like_unlike_post, name="like_unlike_post"),
]

social_network/urls.py
from django.contrib import admin
from django.urls import path, include
from social_network import views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500,handler403, handler400


urlpatterns = [
	path('', views.login_redirect, name='login_redirect'),
    path('admin/', admin.site.urls),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('', include(('home.urls', 'home'), namespace='home')),
    path('profile/', include(('userprofile.urls', 'userprofile'), namespace='userprofile')),
    path('posts/', include(('posts.urls', 'posts'), namespace='posts')),
    path('comments/', include(('comments.urls', 'comments'), namespace='comments')),
    path('friends/', include(('friends.urls', 'friends'), namespace='friends')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userprofile/urls.py
from django.urls import path

from django.contrib.auth import views as auth_views
from . import views

urlpatterns =[
	path('', views.view_profile, name='view_profile'),
	path('view/<pk>/', views.view_profile, name='view_profile_with_pk'),
	path('update/', views.edit_profile, name='edit_profile'),
	path('user/changepassword/', views.change_password, name='change_password'),
	]

home/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

home/forms.py
from django import forms

home/views.py
from django.contrib.auth.models import User

from django.views.generic import TemplateView
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, Http404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages
import random

from friendship.models import Friend, Follow, Block
from posts.models import Post
from posts.forms import PostForm


class HomeView(TemplateView):
	template_name = 'home/home.html'

	def get(self, request):
		current_page = 'home'
		form = PostForm(auto_id=False)
		posts_list = Post.objects.all().order_by('-created')

		me = request.user.userprofile

		paginator = Paginator(posts_list,10)
		page = request.GET.get('page')
		try:
			posts = paginator.page(page)
		except PageNotAnInteger:
			posts = paginator.page(1)
		except EmptyPage:
			posts = paginator.page(paginator.num_pages)

		users = User.objects.exclude(id=request.user.id)
		users_count = users.count()

		args = {
			'form': form, 
			'posts': posts, 
			'users': users,  
			'current_page':current_page,
			'me': me,
			}
		return render(request, self.template_name, args)



	def post(self, request):
		current_page = 'home'
		form = PostForm(request.POST, request.FILES or None, auto_id=False)
		if form.is_valid():
			post = form.save(commit=False)
			post.user = request.user
			post.save()
			messages.success(request, "Post successfully created!")
			text = form.cleaned_data['post']
		else:
			messages.error(request, "Post not created!")

		form = PostForm()
		return redirect('home:home')

		args = {'form': form, 
			'text': text,  
			'current_page':current_page,
			}
		return render(request, self.template_name, args)

		

def search_user(request):
	user_name = request.GET.get('username')
	users_list = User.objects.all()
	users = []
	users_count = 0
	
	if user_name:
		users = users_list.filter(username__icontains=user_name) | users_list.filter(first_name__icontains=user_name, last_name__icontains=user_name) | users_list.filter(first_name__icontains=user_name) | users_list.filter(last_name__icontains=user_name)
		users_count = users.count()

	
	args = {
		'current_page': 'search_user',
		'users': users, 
		'users_count': users_count, 
		'user_name':user_name,
		'me': request.user.userprofile,
		}
	return render(request, 'home/search_user.html', args)
	

home/templates/home/comment_thread.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load custom_filters %}

{% block head %}
<title>Comment Thread</title>
{% endblock %}

{% block body %}

<div class="row justify-content-center">
	<div class="col-md-6">

		<div  id="top" class="mb-4 pr-3">
			<small>
				<a class="float-right" href="{% url 'home:view_post' pk=comment.object_id %}">Back to Post</a>
			</small>

		</div>

		<hr>

		<blockquote>
			<div class="media">
				<img src="{{comment.user.userprofile.image.url}}" alt="" class="rounded-circle mini-mini-profile-pic">
				<div class="media-body">

					<a class="post-header-name" href="{% url 'accounts:view_profile_with_pk' pk=comment.user.pk %}">
						{{comment.user.get_full_name}}
					</a>
					<span> {{comment.content}} </span>
					<div>
						<small class="text-muted">
							{{comment.timestamp|timesince|upto:','}} 
						</small> 
						<small class="text-muted">
							| <a href="#">Reply</a> 
						</small>
						
						{% if post.user == request.user  or comment.user == request.user %}
						<small class="text-muted">
						| <a class="link-color" data-toggle="modal" data-target="#deletecommentmodal_{{comment.id}}">
							Delete
						</a>
						</small>
						{% endif %}
					</div>

					<div>
						<div class="card-body px-2">
							<div class="media">
								<img src="{{request.user.userprofile.image.url}}" alt="" class="rounded-circle mini-mini-profile-pic">
								<div class="media-body">
									<form method="POST" action="."> 
										{% csrf_token %}
										<div class="form-row">
											<div class="col-10 mb-0">
												{{ comment_form|crispy }}
												<input type='hidden' name='parent_id' value='{{ comment.id }}'>
											</div>
											<div class="col-2 mb-0 px-0 text-center">
												<input type='submit' value='Reply' class='link-color custom-button lobster'>
											</div>
										</div>
									</form>
									{% if comment.children.count %}
										<div class="mb-2">
											<small class="text-muted">
												<a href="#" class="all-replies-btn">View all replies</a> ({{comment.children.count}})
											</small>
										</div>
									{% endif %}
								</div>
							</div>
						</div>

						<div class="all-replies">
							{% for child_comment in comment.children %}
							<blockquote>
								<div class="media">
									<img src="{{comment.user.userprofile.image.url}}" alt="" class="rounded-circle mini-mini-profile-pic">
									<div class="media-body">
										<a href="{% url 'accounts:view_profile_with_pk' pk=comment.user.pk %}">
											{{child_comment.user.get_full_name}}
										</a>
										<span> {{child_comment.content}} </span>
										<div>
											<small class="text-muted">
												{{child_comment.timestamp|timesince|upto:','}} 
											</small> 
											<small class="text-muted">
												| <a class="comment-reply-btn" href="#top">Reply</a> 
											</small>
											
											{% if post.user == request.user  or child_comment.user == request.user %}
											<small class="text-muted">
											| <a class="link-color" data-toggle="modal" data-target="#deletereplymodal_{{child_comment.id}}">
												Delete
											</a>
											</small>
											{% endif %}
										</div>
									</div>
								</div>
								{% include 'home/delete_reply_modal.html' %}
							</blockquote>
							{% endfor %}
						</div>
					</div>
				</div>
			</div>
			{% include 'home/delete_comment_modal.html' %}
		</blockquote>
	</div>
</div>

{% endblock %}

home/templates/home/delete_comment_modal.html

<!-- Delete comment -->
<div class="modal fade" id="deletecommentmodal_{{comment.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-header pt-1 pb-1">
				<h5 class="modal-title" id="exampleModalLongTitle">Delete Comment</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				Are you sure you want to delete this comment?
			</div>
			<div class="modal-footer pt-1 pb-1">
				<form method="post" action="{% url 'comments:comment_delete' comment_id=comment.id reply_id=0 previous_page=None %}">
					{% csrf_token %}
					<button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
					<button type="submit" class="btn btn-primary">Delete</button>
				</form>
			</div>
		</div>
	</div>
</div>

home/templates/home/delete_reply_modal.html
<!-- Delete reply to a comment -->
<div class="modal fade" id="deletereplymodal_{{child_comment.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-header pt-1 pb-1">
				<h5 class="modal-title" id="exampleModalLongTitle">Delete Comment</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				Are you sure you want to delete this comment?
			</div>
			<div class="modal-footer pt-1 pb-1">
				<form method="post" action="{% url 'comments:comment_delete' comment_id=comment.id reply_id=child_comment.id previous_page=current_page %}">
					{% csrf_token %}
					<button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
					<button type="submit" class="btn btn-primary">Delete</button>
				</form>
			</div>
		</div>
	</div>
</div>

home/templates/home/friend_list.html
{% for friend in friend_list %}
<div class="card-body">
	<ul class="list-unstyled mb-0">
		<li>
				<img src="{{friend.userprofile.image.url}}" alt="..." class="rounded-circle mini-profile-pic">
				<a href="{% url 'accounts:view_profile_with_pk' pk=friend.pk %}">
					@{{friend.username}}
				</a>
				<a href="{% url 'home:change_friend' operation='remove' pk=friend.pk %}">
					<button type="button" class="margin-left btn btn-outline-info btn-sm float-right">Unfollow</button>
				</a>
		</li>
	</ul>
</div>
{% endfor %}

{% if not following %}
<div>
	<p style="padding: 5px 10px; margin: 0.5rem 0rem">You do not follow anyone.</p>
</div>
{% endif %}

home/templates/home/home.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load friendshiptags %}

{% block head %}
<title>Instabook-Home</title>
{% endblock %}

{% block body %}

<div class="row justify-content-center">
	<div class="col-xl-6 col-md-8 px-2">
		<div class="row" id="post-here">
			<div class="col-3 pr-0 pl-4">
				<div class="profile-thumbnail" style="background-image:url('{{user.userprofile.image.url}}')"></div>
			</div>
			<div class="col-9 pr-4">
				<form method="post" action="{% url 'home:home' %}" class="media-body"  enctype="multipart/form-data">
					<div class="card border-right-0 bg-silver mb-4">

						{% csrf_token %}
						{{ form.post }}

						<div class="form-row">
							<div class="form-group col-12 my-1 px-2">
								<button class="float-right btn-sm btn btn-info mx-1" type="submit"> Post </button>
								<button class="float-right btn-sm btn btn-info mx-1" type="reset"> Reset </button>
								<a data-toggle="modal" data-target="#add-post-picture-{{user.pk}}">
									<button type="button" class="float-left btn btn-info btn-sm mx-1">Photo <i class="fas fa-camera"></i></button>
								</a>
							</div>
						</div>

					{% include 'extras/picture_updation_modals.html' %}

					</div>
				</form>
			</div>
		</div>

		{% for post in posts %}
		{% if post.user in me.friends or post.user == request.user %}
			{% include 'posts/list_posts.html' %}
			{% include 'extras/post_likes_modal.html' %}
		{% endif %}
		{% endfor %}

		{% if posts.count == 0 %}
		<div class="card p-3">
			<p>
				Hello, {{user.first_name}}!<br/>
				Your feed is empty. Follow people to see their posts, photos and more. If you are having any trouble with 'How to use Instabook', readline the guideline <a href="#">here</a>. Happy Instabook time.... blah blah blah.
			</p>
		</div>
		{% endif %}


        {% if posts.has_next or posts.has_previous %}
		<ul class="pagination justify-content-center mb-4">

          {% if posts.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ posts.previous_page_number }}">&larr; Previous</a>
          </li>
          {% else %}
          <li class="page-item disabled">
            <a class="page-link" href="#">&larr; Previous</a>
          </li>
          {% endif %}

          {% if posts.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ posts.next_page_number }}">Next &rarr;</a>
          </li>
          {% else %}
          <li class="page-item disabled">
            <a class="page-link" href="#">Next &rarr;</a>
          </li>
          {% endif %}

        </ul>
        {% endif %}


	</div><!-- /.col -->

	<div class="col-lg-4">

		<div class="media mt-2 mb-3">
			<img src="{{request.user.userprofile.image.url}}" alt="" class="rounded-circle mini-profile-pic">
			<div class="media-body">
				<div class="div-inline line-height-12">
					<a class="fw-55" href="{% url 'userprofile:view_profile' %}">
						<span style="color:#222">{{request.user.username|truncatechars:18}}</span>
					</a><br>
					<small class="text-muted">
						{{request.user.get_full_name}}
					</small>
				</div>
			</div>
		</div>

		
		<div class="card mb-4 network ">
			<div class="card-body">
				<a class="instabook-color small-text" id="switch-requests"> See Sent Requests </a>

				<!-- view recieved requests -->
				<div id="recieved-requests">
					<h4 class="lobster instabook-color mb-3">Recieved Friend Requests {% if me.fr_count %}&#5867; {{me.fr_count}}{% endif %}</h4>

					<ul class="list-unstyled mb-0">
						{% for user in me.friend_requests %}
						<li class="mb-1">
							<div class="media">
								<img src="{{user.userprofile.image.url}}" alt="" class="rounded-circle mini-profile-pic">
								<div class="media-body">
									<div class="div-inline line-height-12">
										<a class="fw-55" href="{% url 'userprofile:view_profile_with_pk' pk=user.pk %}">
											<span style="color:#222">{{user.username|truncatechars:18}}</span>
										</a><br>
										<small class="text-muted">
											{{user.get_full_name}}
										</small>
									</div>
									<div class="div-inline float-right">
										<a class="fw-55 float-right ml-1" href="{% url 'friends:reject-request' id=user.id  %}"><i class="far fa-trash-alt"></i></a>
										<a class="fw-55 float-right" href="{% url 'friends:accept-request' id=user.id  %}">Accept</a>
									</div>
								</div>
							</div>
						</li>
					    {% endfor %}
					</ul>

					{% if not me.friend_requests %}
						<p style="padding: 5px 10px; margin: 0.5rem 0rem">No friend requests</p>
					{% endif %}
				</div>
				<!-- end view recieved requests div-->

				<!-- view-sent requests -->
				<div id="sent-requests">
					<h4 class="lobster instabook-color mb-3">Sent Friend Requests</h4>

					<ul class="list-unstyled mb-0">
						{% for user in me.sent_requests %}
						<li class="mb-1">
							<div class="media">
								<img src="{{user.userprofile.image.url}}" alt="" class="rounded-circle mini-profile-pic">
								<div class="media-body">
									<div class="div-inline line-height-12">
										<a class="fw-55" href="{% url 'userprofile:view_profile_with_pk' pk=user.pk %}">
											<span style="color:#222">{{user.username|truncatechars:18}}</span>
										</a><br>
										<small class="text-muted">
											{{user.get_full_name}}
										</small>
									</div>
									<div class="div-inline float-right">
										<a class="fw-55 float-right link-color" data-toggle="modal" data-target="#cancel_request_{{user.id}}">Requested</a>
									</div>
								</div>
							</div>
							{% include 'extras/friend_modals.html' %}
						</li>
					    {% endfor %}
					</ul>

					{% if not me.sent_requests %}
						<p style="padding: 5px 10px; margin: 0.5rem 0rem">No sent requests</p>
					{% endif %}
				</div>
				<!-- end view sent requests div-->

			</div>
		</div>

		<div class="card mb-4 network">
			<div class="card-body">
				<h4 class="lobster instabook-color mb-3">Suggestions</h4>

				{% if users %}
				<ul class="list-unstyled mb-0">
					{% for user in users %}
					{% if user not in me.friends and user not in me.friend_requests and user not in me.sent_requests and user not in me.blocks and request.user not in user.userprofile.blocks %}
					<li class="mb-1">
						<div class="media">
							<img src="{{user.userprofile.image.url}}" alt="" class="rounded-circle mini-profile-pic">
							<div class="media-body">
								<div class="div-inline line-height-12">
									<a class="fw-55" href="{% url 'userprofile:view_profile_with_pk' pk=user.pk %}">
										<span style="color:#222">{{user.username|truncatechars:18}}</span>
									</a><br>
									<small class="text-muted">
										{{user.get_full_name}}
									</small>
								</div>
								<div class="div-inline float-right">
									<a class="fw-55 float-right link-color" data-toggle="modal" data-target="#send_request_{{user.id}}">Request</a>
								</div>
							</div>
						</div>
						{% include 'extras/friend_modals.html' %}
					</li>
					{% endif %}
				    {% endfor %}
				</ul>
				{% endif %}

			</div>
		</div>

		

		<div class="card mb-4 network">
			<div class="card-body">
				<h4 class="lobster instabook-color mb-3">Friends {% if me.friends_count %}&#5867; {{me.friends_count}}{% endif %}</h4>

				{% if me.friends %}
				<ul class="list-unstyled mb-0">
					{% for user in me.friends %}
					<li class="mb-1">

						<div class="media">
							<img src="{{user.userprofile.image.url}}" alt="" class="rounded-circle mini-profile-pic">
							<div class="media-body">
								<div class="div-inline line-height-12">
									<a class="fw-55" href="{% url 'userprofile:view_profile_with_pk' pk=user.pk %}">
										<span style="color:#222">{{user.username|truncatechars:18}}</span>
									</a><br>
									<small class="text-muted">
										{{user.get_full_name}}
									</small>
								</div>
								<div class="div-inline float-right">
									<a class="fw-55 float-right link-color" data-toggle="modal" data-target="#remove_friend_{{user.id}}">Friends <i class="very-small-icon fas fa-check"></i></a>
								</div>
							</div>
						</div>
						{% include 'extras/friend_modals.html' %}
					</li>
				    {% endfor %}
				</ul>
				{% endif %}

			{% if not me.friends_count %}
				<p style="padding: 5px 10px; margin: 0.5rem 0rem">No friends to display</p>
			{% endif %}

			</div>

		</div>

	</div>
</div><!-- /.row -->


{% endblock %}
				  

{% block js_script %}

window.onload = function(){ 
	var switch_requests = document.querySelector('#switch-requests');
	switch_requests.onclick = function() {
	if (switch_requests.innerHTML == "See Sent Requests") {
		document.querySelector('#recieved-requests').style.display = 'none';
		document.querySelector('#sent-requests').style.display = 'block';
		switch_requests.innerHTML = "See Recieved Requests";
		}
	else {
		document.querySelector('#sent-requests').style.display = 'none';
		document.querySelector('#recieved-requests').style.display = 'block';
		switch_requests.innerHTML = "See Sent Requests";
		}
	}
};

 {% endblock %}  

home/templates/home/list_posts.html
<div class="card mb-4">
	<div class="media px-3 pt-3">
		<img src="{{post.user.userprofile.image.url}}" alt="" class="rounded-circle mini-profile-pic">
		<div class="media-body">
				<div class="div-inline line-height-12">
					<a class="post-header-name" href="{% url 'accounts:view_profile_with_pk' pk=user.pk %}">
						{{post.user.get_full_name}}
					</a><br>
					<small class="text-muted">

						{{post.created|date:"F d, Y"}} at {{post.created|date:"H:i"}}
						{% if post.updated|date:"Y,m,d,H,i" != post.created|date:"Y,m,d,H,i" %}
						| Edited
						{% endif %}

					</small>
				</div>

				{% include 'home/post_options.html' %}

		</div>
	</div>

		{% include 'home/post_content.html' %}

	<div class="card-footer">
		<button class="custom-button instabook-color">
			<i class="far fa-thumbs-up"></i>
		</button>
		
		<a href="{% url 'home:view_post' pk=post.pk %}#comments-section">
			<button class="custom-button instabook-color">
				<i class="far fa-comment"></i>
			</button>
		</a>
		
		<!--<a data-toggle="modal" data-target="#sharepostmodal_{{post.pk}}">-->
			<button class="custom-button instabook-color">
				<i class="far fa-share-square"></i>
			</button>
		<!--</a>-->
	</div>

	<div class="px-4 mb-2">
		<span class="instabook-color post-header-name">256 Likes</span>
		{% if post.comments.count %}
		<a class="float-right post-header-name" href="{% url 'home:view_post' pk=post.pk %}#comments-section">
			<span class="instabook-color">{{post.comments.count}} 
				{% if post.comments.count == 1 %}
				comment
				{% else %}
				comments
				{% endif %}
			</span>
		</a>
		{% endif %}
	</div>

</div>

home/templates/home/post_content.html
<div class="card-body px-4 pb-1">
	<!--{% if post.post_image or post.post_word_count > 50 %}-->
	<p class="card-text line-height-12 px-2">
	<!--{% else %}
	<p class="card-text line-height-12 big-font px-3">
	{% endif %}-->

		{% if 'full_post' not in request.path %}
		    {{post.post|linebreaksbr|truncatewords:50}}
			    {% if post.post_word_count > 50 %}
			    <a href="{% url 'home:view_post' pk=post.pk %}">See more</a>
			    {% endif %}
		    {% else %}
		    {{post.post|linebreaksbr}}
	    {% endif %}
	</p>

</div>
{% if post.post_image %}
	
	{% if 'full_post' not in request.path %}
	<a class="card-text" href="{% url 'home:view_post' pk=post.pk %}">
	{% else %}
	<a class="card-text" data-image-id="" data-toggle="modal" data-title="{{post.user}}'s photo"
	               data-image="{{post.post_image.url}}"
	               data-target="#display-post-picture-{{post.pk}}">
	{% endif %}
	    <img class="mx-auto d-block post-pic" src="{{ post.post_image.url }}" alt="{{post.user.get_full_name}}">
	</a>
{% endif %}

{% include 'accounts/picture_updation_modals.html' %}

home/templates/home/post_options.html

{% load urlify %}

<div class="float-right dropdown dropleft div-inline">
	<a id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true">
		<i class="fas fa-ellipsis-h"></i>
	</a>
	<ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
		{% if 'full_post' not in request.path %}
		<li>
			<a class="dropdown-item" href="{% url 'home:view_post' pk=post.pk %}">
				View Full Post
			</a>
		</li>
		{% endif %}

		{% if post.user == request.user %}
		<li>
			<a class="dropdown-item" href="{% url 'home:edit_post' pk=post.pk previous_page=current_page %}">
				Edit
			</a>
		</li>
		<li>
			<a class="dropdown-item" data-toggle="modal" data-target="#deletepostmodal_{{post.pk}}">
				Delete
			</a>
		</li>
		{% endif %}
	</ul>
</div>


{% if post.user == request.user %}

<!-- Delete Modal -->
<div class="modal fade" id="deletepostmodal_{{post.pk}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-header pt-1 pb-1">
				<h5 class="modal-title" id="exampleModalLongTitle">Delete Post</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				Are you sure you want to delete this post?
			</div>
			<div class="modal-footer pt-1 pb-1">
				<form method="post" action="{% url 'home:delete_post' pk=post.pk previous_page=current_page %}">
					{% csrf_token %}
					<button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
					<button type="submit" class="btn btn-primary">Delete</button>
				</form>
			</div>
		</div>
	</div>
</div>

<!-- Share Post Modal -->
<div class="modal fade" id="sharepostmodal_{{post.pk}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-header pt-1 pb-1">
				<h5 class="modal-title" id="exampleModalLongTitle">Share Post</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				
				<!-- Facebook -->
				<a href="https://www.facebook.com/sharer/sharer.php?u={{request.build_absolute_uri}}">
					<i class="fab fa-facebook-square" style="color:#1877f2"></i>
					Facebook
				</a><br>

				<!-- twitter -->
				<a href="https://twitter.com/home?status={{post.post|truncatechars:80|urlify}}%20{{request.build_absolute_uri}}">
					<i class="fab fa-twitter-square" style="color:#1da1f2"></i>
					Twitter
				</a><br>

				<!-- google plus -->
				<a href='https://plus.google.com/share?url={{request.build_absolute_uri}}'>
					<i class="fab fa-google-plus-square" style="color:#ea4335"></i>
					Share on Google+
				</a><br>

				<!-- linkedin -->
				<a href="https://www.linkedin.com/shareArticle?mini=true&url=http://swiftforentrepreneurs.com/&title=My%20new%20post%20on%20instabook%20&summary={{post.post|urlify}}%20&source={{request.build_absolute_uri}}">
					<i class="fab fa-linkedin" style="color:#007bb5"></i>
					Linkedin
				</a><br>

				<!-- reddit -->
				<a href="http://www.reddit.com/submit?url={{request.build_absolute_uri}}&title=My%20new%20post%20on%20instabook%20">
					<i class="fab fa-reddit-square" style="color:#ff4500"></i>
					Reddit
				</a>

			</div>
		</div>
	</div>
</div>

{% endif %}