accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns =[
	path('login/', auth_views.LoginView.as_view(template_name= 'accounts/login.html'), name='login'),
	path('login_success/', views.login_success, name='login_success'),
	path('logout/', auth_views.LogoutView.as_view(template_name= 'accounts/logout.html'), name='logout'),
	path('register/', views.register, name='register'),

	#reset password urls
	path('resetpassword/', auth_views.PasswordResetView.as_view(), {'template_name': 'accounts/reset_password.html', 'post_reset_redirect': 'accounts:password_reset_done', 'email_template_name': 'accounts/reset_password_email.html'}, name='password_reset'),
	path('resetpassword/done/', auth_views.PasswordResetDoneView.as_view(), {'template_name': 'accounts/reset_password_done.html'}, name='password_reset_done'),
	path('resetpassword/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), {'template_name': 'accounts/reset_password_confirm.html', 'post_reset_redirect': 'accounts:password_reset_complete'}, name='password_reset_confirm'),
	path('resetpassword/complete/', auth_views.PasswordResetCompleteView.as_view(), {'template_name': 'accounts/reset_password_complete.html'}, name='password_reset_complete'),
]

home/urls.py
from django.urls import path
from home.views import HomeView
from . import views

urlpatterns = [
	path('home/', HomeView.as_view(), name='home'),
	path('search_user', views.search_user, name='search_user'),
]

social_network/urls.py
from django.contrib import admin
from django.urls import path, include
from social_network import views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500,handler403, handler400


urlpatterns = [
	path('', views.login_redirect, name='login_redirect'),
    path('admin/', admin.site.urls),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('', include(('home.urls', 'home'), namespace='home')),
    path('profile/', include(('userprofile.urls', 'userprofile'), namespace='userprofile')),
    path('posts/', include(('posts.urls', 'posts'), namespace='posts')),
    path('comments/', include(('comments.urls', 'comments'), namespace='comments')),
    path('friends/', include(('friends.urls', 'friends'), namespace='friends')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userprofile/urls.py
from django.urls import path

from django.contrib.auth import views as auth_views
from . import views

urlpatterns =[
	path('', views.view_profile, name='view_profile'),
	path('view/<pk>/', views.view_profile, name='view_profile_with_pk'),
	path('update/', views.edit_profile, name='edit_profile'),
	path('user/changepassword/', views.change_password, name='change_password'),
	]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegistrationForm(UserCreationForm):
	first_name = forms.CharField(required=True, label="", widget=forms.TextInput(attrs = {'placeholder':'First Name',}))
	last_name = forms.CharField(required=True, label="", widget=forms.TextInput(attrs = {'placeholder':'Last Name',}))
	email = forms.EmailField(required=True, label="", widget=forms.EmailInput(attrs = {'placeholder':'Email',}))
	username = forms.CharField(label='',widget=forms.TextInput(attrs={'placeholder':'Username'}))
	password1 = forms.CharField(label='',widget=forms.PasswordInput(attrs={'placeholder':'Password'}))
	password2 = forms.CharField(label='',widget=forms.PasswordInput(attrs={'placeholder':'Password Confirm'}))

	class Meta:
		model = User
		fields = {
		'username',
		'first_name',
		'last_name',
		'email',
		'password1',
		'password2',
		}

		def save(self, commit=True):
			user = super(RegistrationForm, self).save(commit=False)
			user.first_name = self.cleaned_data['first_name']
			user.last_name = self.cleaned_data['last_name']
			user.email = self.cleaned_data['email']

			if commit:
				user.save()

			return user

accounts/views.py
from django.contrib.auth.models import User

from django.shortcuts import render, redirect
from django.contrib import messages
from django.http import HttpResponse, Http404

from accounts.forms import RegistrationForm

# Create your views here.

def register(request):
	if request.method == "POST":
		form = RegistrationForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data['username']
			messages.success(request, "%s successfully registered!" % username)
			return redirect('home:home')
		else:
			messages.error(request, "Enter a valid email address! Make sure to enter same password in both password fields. If user still not registered, try using a different username.")
			return redirect('accounts:register')
	else:
		form = RegistrationForm()
		args = {'form': form}
		return render(request, 'accounts/register.html', args)

def login_success(request):
	user = request.user
	if not user.userprofile.has_previously_logged_in:
		user.userprofile.has_previously_logged_in = True
		user.userprofile.save()
		return redirect('userprofile:edit_profile')
	else:
		return redirect('home:home')

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block head %}
<title>Change password</title>
{% endblock %}

{% block body %}

<div class="row justify-content-center">
	<div class="col-md-6">
		<div class="content-section">
			<form method="POST">
				{% csrf_token %}
				<fieldset class="form-group">
					<legend class="border-bottom mb-4">Change Password</legend>
					{{ form|crispy }}
				</fieldset>
				<div class="form-group">
					<button class="btn btn-outline-info" type="submit">Change</button>
				</div>
			</form>
			<div class="border-top pt-3">
				<small class="text-muted">
					Don't want to change password? <a class="ml-2" href="{% url 'home:home' %}">Go back</a>
				</small>
			</div>
		</div>

	</div>
</div>



<!--
<form method="POST">
	{% csrf_token %}
	{{ form.as_p }}
	<button class="btn btn-default" type="submit">Submit</button>
	<a href="{% url 'accounts:view_profile' %}"><button class="btn btn-default" type="button">Cancel</button></a>
</form>
-->

{% endblock %}

accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block head %}
<title>Edit Profile</title>
{% endblock %}

{% block body %}

<div class="row justify-content-center">
	<div class="col-md-6">
		<div>
			<div class="card-body">
				<a class="thumbnail" data-image-id="" data-toggle="modal" data-title="{{user.first_name}}'s photo"
                   data-image="{{user.userprofile.image.url}}"
                   data-target="#display-profile-pic-{{user.pk}}">
					<img class="mx-auto d-block profile-page-profile-pic" src="{{ user.userprofile.image.url }}" alt="{{user.first_name}}">
				</a>
			</div>
			<form method="POST" enctype="multipart/form-data">
				{% csrf_token %}
				<div class="small-text mb-4 text-center">
					
					<a class="thumbnail" data-image-id="" data-toggle="modal" data-target="#change-profile-pic-{{user.pk}}">
	                   <button class="btn btn-info btn-sm">Change Photo <i class="fas fa-camera"></i></button>
	               </a>

				</div>

				{% include 'accounts/picture_updation_modals.html' %}

				<fieldset class="form-group">
					<legend class="border-bottom mb-4">Update Profile Info</legend>
						{{u_form.username|as_crispy_field}}
						<div class="form-row">
							<div class="form-group col-md-6 mb-0">
								{{u_form.first_name|as_crispy_field}}
							</div>
							<div class="form-group col-md-6 mb-0">
								{{u_form.last_name|as_crispy_field}}
							</div>
						</div>
						{{u_form.email|as_crispy_field}}
						{{p_form.description|as_crispy_field}}
						<div class="form-row">
							<div class="form-group col-md-8 mb-0">
								{{p_form.education|as_crispy_field}}
							</div>
							<div class="form-group col-md-4 mb-0">
								{{p_form.graduated|as_crispy_field}}
							</div>
						</div>
						<div class="form-row">
							<div class="form-group col-md-8 mb-0">
								{{p_form.company|as_crispy_field}}
							</div>
							<div class="form-group col-md-4 mb-0">
								{{p_form.still_work_here|as_crispy_field}}
							</div>
						</div>
						<div class="form-row">
							<div class="form-group col-md-6 mb-0">
								{{p_form.hometown|as_crispy_field}}
							</div>
							<div class="form-group col-md-6 mb-0">
								{{p_form.current_city|as_crispy_field}}
							</div>
						</div>
						<div class="form-row">
							<div class="form-group col-md-6 mb-0">
								{{p_form.gender|as_crispy_field}}
							</div>
						</div>

				</fieldset>
				<div class="py-3">
					<button class="btn btn-outline-info" type="submit">Update</button>
					<a href="{% url 'accounts:view_profile' %}">
						<button class="btn btn-outline-info" type="button">Cancel</button>
					</a>
				</div>
				<div class="border-top pt-3">
					<small class="text-muted">
						*Do fill the the mandatory fields. <a href="{% url 'accounts:view_profile' %}">Click here</a> to head to Profile.
					</small>
				</div>
			</form>
		</div>
	</div>
</div>
<br><br><br>


{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block head %}
<title>Instabook-login</title>
{% endblock %}

{% block content %}

<div class="content-section">
	<div class="w-100 text-center mb-3">
		<h1 class="lobster instabook-color">Instabook</h1>
		<h4 class="link-color">Sign in</h4>
	</div>
	<hr class="mb-1" width="60%" align="center">
	<form method="POST">
		{% csrf_token %}
		<fieldset class="py-3">
			{{ form|crispy }}
		</fieldset>
		<div class="pt-2 pb-4">
			<button class="btn btn-primary" type="submit">Login</button>
		</div>
	</form>
	<div class="border-top pt-2">
		<small class="text-muted">
			Need An Account? <a class="ml-2" href="{% url 'accounts:register' %}">Sign Up Now</a>
		</small>
	</div>
</div>

{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}

{% block head %}
	<title>Login</title>
{% endblock %}

{% block content %}

<h1>Logged out</h1>
<p>You have been logged out</p>

{% endblock %}

accounts/templates/accounts/picture_updation_modals.html
{% if user == request.user %}
<!-- Add Post picture model -->
<div class="modal fade" id="add-post-picture-{{user.pk}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header pt-1 pb-1">
                <h5 class="modal-title" id="exampleModalLongTitle">Add a Photo</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                {{form.post_image}}
            </div>
            <div class="modal-footer pt-1 pb-1">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Continue</button>
            </div>
        </div>
    </div>
</div>
{% endif %}

<!-- Display Post picture model -->
{% if post.post_image %}
<div class="modal fade" id="display-post-picture-{{post.pk}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header pt-0 pb-0 border-0">
                <h4 class="modal-title" id="image-gallery-title"></h4>
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span>
                </button>
            </div>
            <div class="modal-body pb-3 pr-0 pl-0 pt-0">
                <img id="image-gallery-image" class="img-responsive col-md-12" src="{{ post.post_image.url }}" alt="{{post.user.get_full_name}}">
            </div>
            
        </div>
    </div>
</div>
{% endif %}

<!-- Display Profile picture model -->
<div class="modal fade" id="display-profile-pic-{{user.pk}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header pt-0 pb-0 border-0">
                <h4 class="modal-title" id="image-gallery-title"></h4>
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span>
                </button>
            </div>
            <div class="modal-body pb-3 pr-0 pl-0 pt-0">
                <img id="image-gallery-image" class="img-responsive col-md-12" src="{{ user.userprofile.image.url }}" alt="{{user.get_full_name}}">
            </div>
        </div>
    </div>
</div>

{% if user == request.user %}
<!-- Change Profile picture model -->
<div class="modal fade" id="change-profile-pic-{{user.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header pt-1 pb-1">
                <h5 class="modal-title" id="exampleModalLongTitle">Change Profile Picture</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                {{p_form.image}}
            </div>
            <div class="modal-footer pt-1 pb-1">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Continue</button>
            </div>
        </div>
    </div>
</div>
{% endif %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block head %}
	<title>{{user.first_name}}</title>
{% endblock %}

{% block body %}

<div class="row justify-content-center">
	
	<div class="col-md-4">
		<a class="thumbnail" data-image-id="" data-toggle="modal" data-title="{{user.first_name}}'s photo"
                   data-image="{{user.userprofile.image.url}}"
                   data-target="#display-profile-pic-{{user.pk}}">
			<img class="mx-auto mb-3 mt-2 d-block profile-page-profile-pic" src="{{ user.userprofile.image.url }}" alt="{{user.get_full_name}}">
		</a>
	</div>

	{% include 'accounts/picture_updation_modals.html' %}


	<div class="col-md-6 mt-4">
		<h4 class="lobster">
		{{user.get_full_name}}
		{% if user == request.user %}
		<a href="{% url 'accounts:edit_profile' %}">
		<span class="icon"><i class="fas fa-edit"></i></span>
		</a>
		{% endif %}
		</h4>
		<h6 class="instabook-color">@{{user.username}}</h6>
		<p>{{user.userprofile.description}}</p>

		{% if user == request.user %}

		<div class="text-center">
<!--
		<a data-toggle="modal" data-target="#followers_{{user.pk}}">
			<button class="btn btn-info btn-md" style="margin-right: 12px;">Followers</button>
		</a>
		<a data-toggle="modal" data-target="#following_{{user.pk}}">
			<button class="btn btn-info btn-md" style="margin-left: 12px;">Following</button>
		</a>
-->
		{% endif %}

		</div>

	</div>
</div>

<div class="row justify-content-center mt-4">

	<div class="col-md-4">
		

		<div class="card  mb-4">
			<h5 class="card-header">
				<span class="follow-suggestions icon"><i class="fas fa-globe-americas"></i></i></span>
				Intro
			</h5>

			<div class="card-body">

				<ul class="list-unstyled mb-0">
					{% if user.userprofile.education %}
					<li class="small-text">
						{% if user.userprofile.graduated %}
						Studied {% else %}
						Studies {% endif %}
						at <span class="link-color lobster">{{user.userprofile.education}}</span>
					</li>
					{% endif %}

					{% if user.userprofile.company %}
					<li class="small-text">
						{% if user.userprofile.still_work_here %}
						Works {% else %}
						Worked {% endif %}
						at <span class="link-color lobster">{{user.userprofile.company}}</span>
					</li>
					{% endif %}

					{% if user.userprofile.hometown %}
					<li class="small-text">
						From <span class="link-color">{{user.userprofile.hometown}}</span>
					</li>
					{% endif %}

					{% if user.userprofile.current_city %}
					<li class="small-text">
						Lives in <span class="link-color">{{user.userprofile.current_city}}</span>
					</li>
					{% endif %}

					{% if user.email %}
					<li class="small-text">
						Mail me <span class="link-color">{{user.email}}</span>
					</li>
					{% endif %}

					{% if user.userprofile.website %}
					<li class="small-text">
						Check this out <span class="link-color">
							<a href="{{user.userprofile.website}}">{{user.userprofile.website}}</a>
						</span>
					</li>
					{% endif %}

					{% if user.userprofile.gender %}
					<li class="small-text">
						Gender <span class="link-color">
							{{user.userprofile.gender}}
						</span>
					</li>
					{% endif %}

				</ul>

			</div>
		</div>


		<div class="card mb-4">
			<h5 class="card-header">
				<span class="follow-suggestions icon"><i class="fas fa-user-friends"></i></span>
				Friends
			</h5>

			<div class="card-body">
				<p class="small-text">
				{% if user == request.user %}
					You are not eligible for Friends feature yet!
				{% else %}
					No Friends to display.
				{% endif %}
				</p>
			</div>
		</div>
	</div>

	<div class="col-md-6 profile-content-section">

		{% if not posts %}

		<div class="card mb-4">
			<div class="card-body">
				<p class="small-text">
				{% if user == request.user %}
					You haven't posted anything yet! <br>
					Why not create one? <a href="{% url 'home:home' %}">Click here</a> to write your first post.
				{% else %}
					No posts to display.
				{% endif %}
				</p>

			</div>
		</div>

		{% else %}
			{% for post in posts %}
				{% include "home/list_posts.html" %}
			{% endfor %}
		{% endif %}

	</div><!-- /.col-md-8 -->
</div>

{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block head %}
<title>Instabook-register</title>
{% endblock %}

{% block content %}
<div class="content-section">
	<div class="w-100 text-center mb-3">
		<h1 class="lobster instabook-color">Instabook</h1>
		<h4 class="link-color">Sign up</h4>
	</div>
	<hr class="mb-4" width="60%" align="center">
	<form method="POST">
		{% csrf_token %}
		<fieldset class="form-group">

				{{form.username|as_crispy_field}}
				<div class="form-row">
					<div class="form-group col-md-6 mb-0">
						{{form.first_name|as_crispy_field}}
					</div>
					<div class="form-group col-md-6 mb-0">
						{{form.last_name|as_crispy_field}}
					</div>
				</div>
				{{form.email|as_crispy_field}}
				{{form.password1|as_crispy_field}}
				{{form.password2|as_crispy_field}}
				
		</fieldset>
		<div class="pt-2 pb-4">
			<button class="btn btn-primary" type="submit">Sign Up</button>
		</div>
	</form>
	<div class="border-top pt-2">
		<small class="text-muted">
			Already Have An Account? <a class="ml-2" href="{% url 'accounts:login' %}">Sign In</a>
		</small>
	</div>
</div>
<br><br>
{% endblock %}

accounts/templates/accounts/reset_password.html
{% extends 'base.html' %}

{% block head %}
	<title>Reset password</title>
{% endblock %}

{% block body %}

<h1>Reset Password</h1>
<p>Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.</p>
<form method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<button class="btn btn-default" type="submit">Reset my password</button>
</form>

{% endblock %}

accounts/templates/accounts/reset_password_complete.html
{% extends 'base.html' %}

{% block head %}
	<title>Password reset Complete</title>
{% endblock %}

{% block body %}

<h1>Password reset complete</h1>
<p>Your password has been set. You may go ahead and log in now.</p>

<p><a href="{% url 'accounts:login' %}">Login</a></p>

{% endblock %}

accounts/templates/accounts/reset_password_confirm.html
{% extends 'base.html' %}

{% block head %}
	<title>Password reset confirm</title>
{% endblock %}

{% block body %}

<h1>Enter new password:</h1>
<form method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<button class="btn btn-default" type="submit">Reset password</button>
</form>

{% endblock %}

accounts/templates/accounts/reset_password_done.html
{% extends 'base.html' %}

{% block head %}
	<title>Password reset sent</title>
{% endblock %}

{% block body %}

<h1>Password reset sent</h1>
<p>We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.</p>
<p>If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.</p>

{% endblock %}





accounts/templates/accounts/reset_password_email.html
{% load i18n %}{% autoescape off %}

{% blocktrans %}You're recieving this email because you requested a password reset for you user account {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %}{{ user.get_username}}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team {% endblocktrans %}

{% endautoescape %}