comments/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('<id>/', views.comment_thread, name='comment_thread'),
	path('delete/<int:comment_id>/<int:reply_id>/', views.comment_delete, name='comment_delete'),
]

home/urls.py
from django.urls import path
from home.views import HomeView
from . import views

urlpatterns = [
	path('home/', HomeView.as_view(), name='home'),
	path('search_user', views.search_user, name='search_user'),
]

posts/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('<pk>/full_post', views.view_post, name='view_post'),
	path('<pk>/edit/next?=<previous_page>/', views.edit_post, name='edit_post'),
	path('<pk>/edit/cancel/next?=<previous_page>/', views.cancel_post_activity, name='cancel_post_activity'),
	path('<pk>/delete/', views.delete_post, name='delete_post'),
	path('<pk>/<operation>/', views.like_unlike_post, name="like_unlike_post"),
]

social_network/urls.py
from django.contrib import admin
from django.urls import path, include
from social_network import views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500,handler403, handler400


urlpatterns = [
	path('', views.login_redirect, name='login_redirect'),
    path('admin/', admin.site.urls),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('', include(('home.urls', 'home'), namespace='home')),
    path('profile/', include(('userprofile.urls', 'userprofile'), namespace='userprofile')),
    path('posts/', include(('posts.urls', 'posts'), namespace='posts')),
    path('comments/', include(('comments.urls', 'comments'), namespace='comments')),
    path('friends/', include(('friends.urls', 'friends'), namespace='friends')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userprofile/urls.py
from django.urls import path

from django.contrib.auth import views as auth_views
from . import views

urlpatterns =[
	path('', views.view_profile, name='view_profile'),
	path('view/<pk>/', views.view_profile, name='view_profile_with_pk'),
	path('update/', views.edit_profile, name='edit_profile'),
	path('user/changepassword/', views.change_password, name='change_password'),
	]

posts/models.py
from django.contrib.auth.models import User

from django.db import models
from django.db.models.signals import post_save, pre_save
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericRelation
from django.utils.text import slugify

from comments.models import Comment

# Create your models here.
def upload_location(instance, filename):
	return "post_images/%s/%s" % (instance.user, filename)

class Post(models.Model):
	post = models.TextField()
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	#slug = models.SlugField(unique=True)
	post_image = models.ImageField(upload_to=upload_location, null=True, blank=True, 
		height_field="height_field", 
		width_field="width_field")
	height_field = models.IntegerField(default=0)
	width_field = models.IntegerField(default=0)
	likes = models.ManyToManyField(User, related_name="likes", blank=True)

	post_obj = GenericRelation(Comment, object_id_field="object_id", related_query_name="post")

	def __str__(self):
		return str(self.user) + ' wrote... ' + str(self.post)

	def add_like(self, liker):
		self.likes.add(liker)

	def remove_like(self, unliker):
		self.likes.remove(unliker)

	@property
	def count_likes(self):
		return self.likes.count()

	@property
	def post_word_count(self):
		text = self.post
		count = len(text.split())
		return count

	@property
	def comments(self):
		instance = self
		qs = Comment.objects.filter_by_instance(instance)
		return qs

	@property
	def get_content_type(self):
		instance = self
		content_type = ContentType.objects.get_for_model(instance.__class__)
		return content_type


posts/forms.py
from django import forms
from django.forms import ModelForm
from posts.models import Post

class PostForm(ModelForm):
	post = forms.CharField(widget=forms.Textarea(
			attrs = {
				'class':'form-control custom-textarea',
				'placeholder':'Write a post...',
				'rows':4,
			}
		))

	post_image = forms.ImageField(label='Image',required=False, 
			error_messages = {'invalid':"Image files only"}, 
			widget=forms.FileInput()
			)

	class Meta:
		model = Post
		fields = ['post', 'post_image']

class EditPostForm(ModelForm):
	post = forms.CharField(widget=forms.Textarea(
			attrs = {
				'class':'form-control',
				'rows':8,
			}
		))
	post_image = forms.ImageField(label='Image',required=False, 
			error_messages = {'invalid':"Image files only"}, 
			widget=forms.FileInput()
			)

	class Meta:
		model = Post
		fields = ['post','post_image']

		

posts/views.py
from django.contrib.auth.models import User

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.contenttypes.models import ContentType
from django.views.generic import TemplateView
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.contrib import messages

from friendship.models import Friend, Follow, Block
from posts.forms import PostForm, EditPostForm
from posts.models import *

from comments.models import Comment
from comments.forms import CommentForm


def view_post(request, pk):
	current_page = 'view-post'
	try:
		post = Post.objects.get(pk=pk)
	except:
		raise Http404

	if not (request.user == post.user or request.user in Friend.objects.friends(post.user)) or request.user in Block.objects.blocking(post.user):
		reponse = HttpResponse("Permission denied.")
		reponse.status_code = 403
		return reponse

	initial_data = {
		'content_type': post.get_content_type,
		'object_id': post.id,
	}

	comment_form = CommentForm(request.POST or None, initial=initial_data)
	if comment_form.is_valid():
		c_type = comment_form.cleaned_data.get("content_type")
		content_type = ContentType.objects.get(model=c_type)
		obj_id = comment_form.cleaned_data.get("object_id")
		content_data = comment_form.cleaned_data.get("content")
		parent_obj = None
		try:
			parent_id = int(request.POST.get("parent_id"))
		except:
			parent_id = None

		if parent_id:
			parent_qs = Comment.objects.filter(id=parent_id)
			if parent_qs.exists() and parent_qs.count() == 1:
				parent_obj = parent_qs.first()

		new_comment, created = Comment.objects.get_or_create(
										user=request.user,
										content_type=content_type,
										object_id=obj_id,
										content=content_data,
										parent=parent_obj,
										)
		return redirect("posts:view_post",pk=pk)

	comments = Comment.objects.filter_by_instance(post)

	args = {'post': post, 
		'comments':comments,
		'current_page': current_page,
		'comment_form': comment_form,
		'me': request.user.userprofile,
		}
	return render(request, 'posts/view_post.html', args)


def delete_post(request, pk, previous_page=None):
	try:
		post = Post.objects.get(pk=pk)
	except:
		raise Http404

	if post.user != request.user:
		reponse = HttpResponse("Permission denied.")
		reponse.status_code = 403
		return reponse

	post.delete()
	messages.success(request, "Post successfully deleted!")
	return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def edit_post(request, pk, previous_page=None):
	try:
		post = Post.objects.get(pk=pk)
	except:
		raise Http404

	if post.user != request.user:
		reponse = HttpResponse("Permission denied.")
		reponse.status_code = 403
		return reponse

	if request.method == 'POST':
		form = EditPostForm(request.POST, request.FILES, instance=post, auto_id=False)
		if form.is_valid():
			post.save()
			messages.success(request, "Post successfully updated!")
			return redirect('posts:view_post', pk=pk)
	else:
		form = EditPostForm(instance=post, auto_id=False)
		args = {'form': form, 
			'post': post, 
			'previous_page':previous_page
			}
		return render(request, 'posts/edit_post.html', args)


def cancel_post_activity(request, pk, previous_page=None):
	if previous_page == 'profile':
		return redirect('userprofile:view_profile')
	elif previous_page == 'view-post':
		return redirect('posts:view_post', pk=pk)
	else:
		return redirect('home:home')

def like_unlike_post(request, pk, operation):
	try:
		post = Post.objects.get(pk=pk)
	except:
		raise Http404

	if not (request.user == post.user or request.user in post.user.userprofile.friends):
		reponse = HttpResponse("Permission denied.")
		reponse.status_code = 403
		return reponse

	if operation == 'unlike':
		post.remove_like(request.user)
	elif operation =='like':
		post.add_like(request.user)

	return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

posts/templates/posts/comment_thread.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load custom_filters %}

{% block head %}
<title>{{comment.content_object.user.username}}-{{comment.content_object.post|truncatechars:50}}</title>
{% endblock %}

{% block body %}

<div class="row justify-content-center">
	<div class="col-md-6">

		<div  id="top" class="mb-4 pr-3">
			<small>
				<a class="instabook-color float-right" href="{% url 'posts:view_post' pk=comment.object_id %}">Back to Post</a>
			</small>

		</div>

		<hr>

		<blockquote>
			<div class="media">
				<img src="{{comment.user.userprofile.image.url}}" alt="" class="rounded-circle mini-mini-profile-pic">
				<div class="media-body">

					{% if comment.user in me.blocks or request.user in comment.user.userprofile.blocks %}
					<span class="fw-55">{{comment.user.username}}</span>
					{% else %}
					<a href="{% url 'userprofile:view_profile_with_pk' pk=comment.user.pk %}">
						<span class="fw-55">{{comment.user.username}}</span>
					</a>
					{% endif %}

					<span> {{comment.content}} </span>
					<div>
						<small class="text-muted">
							{{comment.timestamp|timesince|upto:','}} 
						</small> 
						<small class="text-muted">
							| <a class="instabook-color" href="#"><span class="instabook-color">Reply</span></a> 
						</small>
						
						{% if post.user == request.user  or comment.user == request.user %}
						<small class="text-muted">
						| <a class="link-color" data-toggle="modal" data-target="#deletecommentmodal_{{comment.id}}">
							Delete
						</a>
						</small>
						{% endif %}
					</div>

					<div>
						<div class="card-body px-2">
							<div class="media">
								<img src="{{request.user.userprofile.image.url}}" alt="" class="rounded-circle mini-mini-profile-pic">
								<div class="media-body">
									<form method="POST" action="."> 
										{% csrf_token %}
										<div class="form-row">
											<div class="col-10 mb-0">
												{{ comment_form|crispy }}
												<input type='hidden' name='parent_id' value='{{ comment.id }}'>
											</div>
											<div class="col-2 mb-0 px-0 text-center">
												<input type='submit' value='Reply' class='instabook-color custom-button lobster'>
											</div>
										</div>
									</form>
									{% if comment.children.count %}
										<div class="mb-2">
											<small class="text-muted">
												<a href="#" class="all-replies-btn">View all replies</a> ({{comment.children.count}})
											</small>
										</div>
									{% endif %}
								</div>
							</div>
						</div>

						<div class="all-replies">
							{% for child_comment in comment.children %}
							<blockquote>
								<div class="media">
									<img src="{{comment.user.userprofile.image.url}}" alt="" class="rounded-circle mini-mini-profile-pic">
									<div class="media-body">

										{% if child_comment.user in me.blocks %}
										<span class="fw-55">{{child_comment.user.username}}</span>
										{% else %}
										<a href="{% url 'userprofile:view_profile_with_pk' pk=child_comment.user.pk %}">
											<span class="fw-55">{{child_comment.user.username}}</span>
										</a>
										{% endif %}

										<span> {{child_comment.content}} </span>
										<div>
											<small class="text-muted">
												{{child_comment.timestamp|timesince|upto:','}} 
											</small> 
											<small class="text-muted">
												| <a class="comment-reply-btn" href="#top"><span class="instabook-color">Reply</span></a> 
											</small>
											
											{% if post.user == request.user  or child_comment.user == request.user %}
											<small class="text-muted">
											| <a class="link-color" data-toggle="modal" data-target="#deletereplymodal_{{child_comment.id}}">
												Delete
											</a>
											</small>
											{% endif %}
										</div>
									</div>
								</div>
								{% include 'posts/delete_reply_modal.html' %}
							</blockquote>
							{% endfor %}
						</div>
					</div>
				</div>
			</div>
			{% include 'posts/delete_comment_modal.html' %}
		</blockquote>
	</div>
</div>

{% endblock %}

posts/templates/posts/delete_comment_modal.html

<!-- Delete comment -->
<div class="modal fade" id="deletecommentmodal_{{comment.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content text-center">
			<div class="modal-body">
                <p class="mt-2">Are you sure you want to delete this comment?</p>
            </div>
            <div class="modal-footer py-2">
                <div class="row w-100">
                	<div class="col-6 border-right">
                		<a data-dismiss="modal">Cancel</a>
                	</div>
                	<div class="col-6">
                		<a href="{% url 'comments:comment_delete' comment_id=comment.id reply_id=0 %}">Delete</a>
                	</div>
                </div>
            </div>
		</div>
	</div>
</div>

posts/templates/posts/delete_reply_modal.html
<!-- Delete reply to a comment -->
<div class="modal fade" id="deletereplymodal_{{child_comment.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content text-center">

			<div class="modal-body">
                <p class="mt-2">Are you sure you want to delete this comment?</p>
            </div>
            <div class="modal-footer py-2">
                <div class="row w-100">
                	<div class="col-6 border-right">
                		<a data-dismiss="modal">Cancel</a>
                	</div>
                	<div class="col-6">
                		<a href="{% url 'comments:comment_delete' comment_id=comment.id reply_id=child_comment.id %}">Delete</a>
                	</div>
                </div>
            </div>
		</div>
	</div>
</div>

posts/templates/posts/list_posts.html
<div class="card mb-4">
	<div class="media px-3 pt-3">
		<img src="{{post.user.userprofile.image.url}}" alt="" class="rounded-circle mini-profile-pic">
		<div class="media-body">
				<div class="div-inline line-height-12">
					<a class="post-header-name" href="{% url 'userprofile:view_profile_with_pk' pk=user.pk %}">
						{{post.user.username}}
					</a><br>
					<small class="text-muted">

						{{post.created|date:"F d, Y"}} at {{post.created|date:"H:i"}}
						{% if post.updated|date:"Y,m,d,H,i" != post.created|date:"Y,m,d,H,i" %}
						| Edited
						{% endif %}

					</small>
				</div>

				{% include 'posts/post_options.html' %}

		</div>
	</div>

		{% include 'posts/post_content.html' %}

	<div class="card-footer">
		{% if request.user in post.likes.all %}
		<a href="{% url 'posts:like_unlike_post' pk=post.pk operation='unlike' %}">
			<button class="custom-button link-color">
				<i class="far fa-thumbs-up"></i>
			</button>
		</a>
		{% else %}
		<a href="{% url 'posts:like_unlike_post' pk=post.pk operation='like' %}">
			<button class="custom-button instabook-color">
				<i class="far fa-thumbs-up"></i>
			</button>
		</a>
		{% endif %}
		
		<a href="{% url 'posts:view_post' pk=post.pk %}#comments-section">
			<button class="custom-button instabook-color">
				<i class="far fa-comment"></i>
			</button>
		</a>
		
		<!--<a data-toggle="modal" data-target="#sharepostmodal_{{post.pk}}">-->
			<button class="custom-button instabook-color">
				<i class="far fa-share-square"></i>
			</button>
		<!--</a>-->

	</div>

	<div id="comments-section" class="px-4 mb-2">

		{% if post.likes.count %}
		<a id="" class="post-header-name" data-toggle="modal" data-target="#post_likes_{{post.id}}">
			{% if request.user in post.likes.all %}
			<span class="link-color">
			{% else %}
			<span class="instabook-color">
			{% endif %}
				{{post.likes.count}} 
				{% if post.likes.count == 1 %}
				Like
				{% else %}
				Likes
				{% endif %}
			</span>
		</a>
		{% else %}
			<span class="instabook-color">Be the first to like it</span>
		{% endif %}

		{% if post.comments.count %}
		<a class="float-right post-header-name" href="{% url 'posts:view_post' pk=post.pk %}#comments-section">
			<span class="instabook-color">{{post.comments.count}} 
				{% if post.comments.count == 1 %}
				comment
				{% else %}
				comments
				{% endif %}
			</span>
		</a>
		{% endif %}

	</div>

</div>

posts/templates/posts/post_options.html

{% load urlify %}

<div class="float-right dropdown div-inline">
	<a id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true">
		<i class="fas fa-ellipsis-h"></i>
	</a>
	<ul class="dropdown-menu dropdown-menu-right" role="menu" aria-labelledby="dropdownMenu1">
		{% if 'full_post' not in request.path %}
		<li>
			<a class="dropdown-item" href="{% url 'posts:view_post' pk=post.pk %}">
				View Full Post
			</a>
		</li>
		{% endif %}

		{% if post.user == request.user %}
		<li>
			<a class="dropdown-item" href="{% url 'posts:edit_post' pk=post.pk previous_page=current_page %}">
				Edit
			</a>
		</li>
		<li>
			<a class="dropdown-item" data-toggle="modal" data-target="#deletepostmodal_{{post.pk}}">
				Delete
			</a>
		</li>
		{% endif %}
	</ul>
</div>


{% if post.user == request.user %}

<!-- Delete post Modal -->
<div class="modal fade" id="deletepostmodal_{{post.pk}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content text-center">
			<div class="modal-body">
                <p class="mt-2">Are you sure you want to delete this post?</p>
            </div>
            <div class="modal-footer py-2">
                <div class="row w-100">
                	<div class="col-6 border-right">
                		<a data-dismiss="modal">Cancel</a>
                	</div>
                	<div class="col-6">
                		<a href="{% url 'posts:delete_post' pk=post.pk  %}">Delete</a>
                	</div>
                </div>
            </div>
		</div>
	</div>
</div>

{% endif %}

<!-- Share Post Modal -->
<!--
<div class="modal fade" id="sharepostmodal_{{post.pk}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-header pt-1 pb-1">
				<h5 class="modal-title" id="exampleModalLongTitle">Share Post</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
		-->		
				<!-- Facebook -->
				<!--
				<a href="https://www.facebook.com/sharer/sharer.php?u={{request.build_absolute_uri}}">
					<i class="fab fa-facebook-square" style="color:#1877f2"></i>
					Facebook
				</a><br>
			-->

				<!-- twitter -->
				<!--
				<a href="https://twitter.com/home?status={{post.post|truncatechars:80|urlify}}%20{{request.build_absolute_uri}}">
					<i class="fab fa-twitter-square" style="color:#1da1f2"></i>
					Twitter
				</a><br>
			-->

				<!-- google plus -->
				<!--
				<a href='https://plus.google.com/share?url={{request.build_absolute_uri}}'>
					<i class="fab fa-google-plus-square" style="color:#ea4335"></i>
					Share on Google+
				</a><br>
			-->

				<!-- linkedin -->
				<!--
				<a href="https://www.linkedin.com/shareArticle?mini=true&url=http://swiftforentrepreneurs.com/&title=My%20new%20post%20on%20instabook%20&summary={{post.post|urlify}}%20&source={{request.build_absolute_uri}}">
					<i class="fab fa-linkedin" style="color:#007bb5"></i>
					Linkedin
				</a><br>
			-->

				<!-- reddit -->
				<!--
				<a href="http://www.reddit.com/submit?url={{request.build_absolute_uri}}&title=My%20new%20post%20on%20instabook%20">
					<i class="fab fa-reddit-square" style="color:#ff4500"></i>
					Reddit
				</a>

			</div>
		</div>
	</div>
</div>
-->

posts/templates/posts/view_post.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load custom_filters %}

{% block head %}
<title>{{post.user.username}}-{{post.post|truncatechars:50}}</title>
{% endblock %}

{% block body %}

<div class="row justify-content-center">
	<div class="col-md-6 px-2">
		<div class="card mb-3">
			<div class="media px-3 pt-3">
				<img src="{{post.user.userprofile.image.url}}" alt="post.user.get_full_name" class="rounded-circle mini-profile-pic">
				<div class="media-body">
					<div class="div-inline line-height-12">
						<a class="post-header-name" href="{% url 'userprofile:view_profile_with_pk' pk=user.pk %}">
							{{post.user.username}}
						</a><br>
						<small class="text-muted">

							{{post.created|date:"F d, Y"}} at {{post.created|date:"H:i"}}
							{% if post.updated|date:"Y,m,d,H,i" != post.created|date:"Y,m,d,H,i" %}
							| Edited
							{% endif %}

						</small>
					</div>
					{% if post.user == request.user %}
					{% include 'posts/post_options.html' %}
					{% endif %}
				</div>
			</div>

			{% include 'posts/post_content.html' %}
			{% include 'extras/post_likes_modal.html' %}

			<div class="card-footer">
				{% if request.user in post.likes.all %}
				<a href="{% url 'posts:like_unlike_post' pk=post.pk operation='unlike'  %}">
					<button class="custom-button link-color">
						<i class="far fa-thumbs-up"></i>
					</button>
				</a>
				{% else %}
				<a href="{% url 'posts:like_unlike_post' pk=post.pk operation='like'  %}">
					<button class="custom-button instabook-color">
						<i class="far fa-thumbs-up"></i>
					</button>
				</a>
				{% endif %}
			
				<button class="custom-button instabook-color">
					<i class="far fa-comment"></i>
				</button>
			
				<button class="custom-button instabook-color">
					<!--<a data-toggle="modal" data-target="#sharepostmodal_{{post.pk}}">-->
					<i class="far fa-share-square"></i>
					<!--</a>-->
				</button>

			</div>

			<div id="comments-section" class="px-4 mb-2">

				{% if post.likes.count %}
				<a id="" class="post-header-name"  data-toggle="modal" data-target="#post_likes_{{post.id}}">
					{% if request.user in post.likes.all %}
					<span class="link-color">
					{% else %}
					<span class="instabook-color">
					{% endif %}
						{{post.likes.count}} 
						{% if post.likes.count == 1 %}
						Like
						{% else %}
						Likes
						{% endif %}
					</span>
				</a>
				{% else %}
				<span class="instabook-color">Be the first to like it</span>
				{% endif %}

				{% if post.comments.count %}
				<a id="all-comments-btn" class="float-right post-header-name" href="#comments-section">
					<span class="instabook-color">{{post.comments.count}} 
						{% if post.comments.count == 1 %}
						comment
						{% else %}
						comments
						{% endif %}
					</span>
				</a>
				{% endif %}

			</div>
		</div>

			<div class="card-body px-3">
				
				<div class="media">
					<img src="{{request.user.userprofile.image.url}}" alt="" class="rounded-circle mini-mini-profile-pic">
					<div class="media-body">
						<form method="POST" action="{% url 'posts:view_post' pk=post.pk %}"> 
							{% csrf_token %}
							<div class="form-row">
								<div class="col-10 mb-0">
									{{ comment_form|crispy }}
								</div>
								<div class="col-2 mb-0 px-0 text-center">
									<input type='submit' value='Comment' class='instabook-color custom-button lobster'>
								</div>
							</div>
						</form>
					</div>
				</div>
				
			</div>


			<div class="card-body px-4 pt-0">
				{% for comment in comments %}
				<blockquote class="mb-1">
					<div class="media">
						<img src="{{comment.user.userprofile.image.url}}" alt="" class="rounded-circle mini-mini-profile-pic">
						<div class="media-body">

							{% if comment.user in me.blocks or request.user in comment.user.userprofile.blocks %}
							<span class="fw-55">{{comment.user.username}}</span>
							{% else %}
							<a href="{% url 'userprofile:view_profile_with_pk' pk=comment.user.pk %}">
								<span class="fw-55">{{comment.user.username}}</span>
							</a>
							{% endif %}

							<span> {{comment.content}} </span>
							<div id="comment-options">
								<small class="text-muted">
									{{comment.timestamp|timesince|upto:','}} 
								</small> 
								<small class="text-muted">
									| <a class="comment-reply-btn" href="#"><span class="instabook-color">Reply</span></a> 
								</small>
								
								{% if post.user == request.user  or comment.user == request.user %}
								<small class="text-muted">
								| <a class="instabook-color" data-toggle="modal" data-target="#deletecommentmodal_{{comment.id}}">
									Delete
								</a> 
								</small>
								{% endif %}
								<small class="text-muted">
									{% if comment.children.count >= 4 %}
									| <a class="instabook-color" href="{{comment.get_absolute_url}}">Thread</a>
									{% endif %}
								</small>
							</div>

							<div class="comment-reply">
								<div id="replies" class="card-body px-2 pb-2">
									<div class="media">
										<img src="{{request.user.userprofile.image.url}}" alt="" class="rounded-circle mini-mini-profile-pic">
										<div class="media-body">
											<form method="POST" action="{% url 'posts:view_post' pk=post.pk %}"> 
												{% csrf_token %}
												<div class="form-row">
													<div class="col-10 mb-0">
														{{ comment_form|crispy }}
														<input type='hidden' name='parent_id' value='{{ comment.id }}'>
													</div>
													<div class="col-2 mb-0 px-0 text-center">
														<input type='submit' value='Reply' class='instabook-color custom-button lobster'>
													</div>
												</div>
											</form>
											{% if comment.children.count %}
												<div class="mb-2">
													<small class="text-muted">
														<a href="#" class="all-replies-btn">View all replies</a> ({{comment.children.count}})
													</small>
												</div>
											{% endif %}
										</div>
									</div>
								</div>

								<div class="all-replies">
									{% for child_comment in comment.children %}
									<blockquote>
										<div class="media">
											<img src="{{comment.user.userprofile.image.url}}" alt="" class="rounded-circle mini-mini-profile-pic">
											<div class="media-body">

												{% if child_comment.user in me.blocks %}
												<span class="fw-55">{{child_comment.user.username}}</span>
												{% else %}
												<a href="{% url 'userprofile:view_profile_with_pk' pk=child_comment.user.pk %}">
													<span class="fw-55">{{child_comment.user.username}}</span>
												</a>
												{% endif %}

												<span> {{child_comment.content}} </span>
												<div>
													<small class="text-muted">
														{{child_comment.timestamp|timesince|upto:','}}
													</small> 
													<small class="text-muted">
														| <a class="instabook-color comment-reply-btn" href="#"><span class="instabook-color">Reply</span></a>
													</small>
													
													{% if post.user == request.user  or child_comment.user == request.user %}
													<small class="text-muted">
														| <a class="instabook-color" data-toggle="modal" data-target="#deletereplymodal_{{child_comment.id}}">
															Delete
														</a>
													</small>
													{% endif %}
												</div>
											</div>
										</div>
										{% include 'posts/delete_reply_modal.html' %}
									</blockquote>
									{% endfor %}
								</div>
							</div>
						</div>
					</div>
					{% include 'posts/delete_comment_modal.html' %}
				</blockquote>
				{% endfor %}
			</div>
	</div>
</div>

{% endblock %}